#!/usr/bin/env node
/**
 * Assert that the committed ABIs match the contracts.
 *
 * ## Why this exists
 * `shared/src/abi.ts` and `shared/src/bytecode.ts` are generated by
 * `contracts/scripts/export-abi.cjs` and **committed**. The app imports from
 * them; it never reads Hardhat's build artifacts. That is what lets the Docker
 * image install production dependencies only — no Hardhat, no solc, no compile
 * step — which took the build's peak disk from ~700 MB to ~150 MB after a host
 * hit `ENOSPC: no space left on device`.
 *
 * The trade is that a generated file is now load-bearing, so it must not be able
 * to drift silently. Two checks:
 *
 *   1. **Structural** (no compiler needed): the exporter, the contract sources
 *      and the generated files all agree on the same set of contracts. Catches
 *      adding or renaming a contract without regenerating.
 *   2. **Exact** (`--compiled`, for CI after `npm run compile`): the generated
 *      files are unchanged in the working tree, i.e. compiling reproduced them
 *      byte for byte. This is the real assertion, and it is why the Docker build
 *      can trust them.
 *
 * The export names are read out of `export-abi.cjs` rather than derived from a
 * guessed convention — a first version of this script assumed
 * `TesseraAMM → tesseraAMMAbi` and flagged three false failures, because the
 * real names are `tesseraAmmAbi` and `mockUsdcAbi`. The exporter is the authority
 * on what it writes, so it is what gets parsed.
 *
 * Run: `npm run abi:check`   ·   CI: `npm run abi:check -- --compiled`
 */
import { readFileSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const EXACT = process.argv.includes("--compiled");

let fails = 0;
const check = (ok, label, detail = "") => {
  if (!ok) fails++;
  console.log(`${ok ? "PASS" : "FAIL"} — ${label}${!ok && detail ? ` (${detail})` : ""}`);
};

const exporter = readFileSync(path.join(ROOT, "contracts/scripts/export-abi.cjs"), "utf8");
const abiTs = readFileSync(path.join(ROOT, "shared/src/abi.ts"), "utf8");
const bytecodeTs = readFileSync(path.join(ROOT, "shared/src/bytecode.ts"), "utf8");

/**
 * Contracts with no ABI to export, and why. Anything not covered by the exporter
 * has to be listed here deliberately — that is what makes a *new* uncovered
 * contract a failure rather than a silent omission.
 */
const NOT_EXPORTED = {
  ReentrancyGuard: "abstract base contract, never deployed on its own",
  MockAggregator: "test-only Chainlink feed stub, used from the Hardhat tests directly",
  MockFlashBorrower: "test-only flash-loan callback, used from the Hardhat tests directly",
  MockSharePool: "test-only stand-in for the pool's share accounting, used from the emissions tests directly",
  MockFundSink: "test-only pull-funding recipient, used from the emitter tests directly",
  MockRevertingSink: "test-only always-failing recipient, proves one bad sink cannot block the others",
};

// --- 1. structural ----------------------------------------------------------

// What the exporter reads, and what it promises to write.
const readsArtifacts = [...exporter.matchAll(/readArtifact\("([A-Za-z0-9_]+)"\)/g)].map((m) => m[1]);
const writesAbi = [...exporter.matchAll(/export const (\w+)Abi\b/g)].map((m) => m[1]);
const writesBytecode = [...exporter.matchAll(/export const (\w+)Bytecode\b/g)].map((m) => m[1]);
check(readsArtifacts.length > 0 && writesAbi.length > 0, "the exporter declares what it covers",
  `${readsArtifacts.length} artifacts, ${writesAbi.length} ABI exports`);

// Every contract the exporter reads must still exist as a source, or `compile`
// will fail on the next run and nobody will know why until then.
const sources = readdirSync(path.join(ROOT, "contracts/contracts"))
  .filter((f) => f.endsWith(".sol"))
  .map((f) => f.replace(/\.sol$/, ""));
const vanished = readsArtifacts.filter((n) => !sources.includes(n));
check(!vanished.length, `every contract the exporter reads still exists (${readsArtifacts.length})`,
  vanished.length ? `${vanished.join(", ")} — renamed or deleted; update export-abi.cjs` : "");

// Every concrete contract is either exported or deliberately excluded.
const concrete = sources.filter((name) => {
  const src = readFileSync(path.join(ROOT, "contracts/contracts", `${name}.sol`), "utf8");
  return new RegExp(`^\\s*contract\\s+${name}\\b`, "m").test(src);
});
const uncovered = concrete.filter((n) => !readsArtifacts.includes(n) && !(n in NOT_EXPORTED));
check(!uncovered.length, `every concrete contract is exported or explicitly excluded (${concrete.length})`,
  uncovered.length
    ? `${uncovered.join(", ")} — add to export-abi.cjs, or to NOT_EXPORTED in this script with a reason`
    : "");

// Anything on the exclusion list should actually exist, so the list cannot rot.
const staleExclusions = Object.keys(NOT_EXPORTED).filter((n) => !sources.includes(n));
check(!staleExclusions.length, "the exclusion list has no stale entries", staleExclusions.join(", "));

// The generated files must contain everything the exporter promises.
// Word-boundary matched, not `includes`. A substring test passes on
// `tesseraAmmAbiRENAMED`, so it would wave through exactly the drift this is
// meant to catch — verified by breaking it on purpose.
const declares = (src, name, kind) => new RegExp(`export const ${name}${kind}\\b`).test(src);
const missingAbi = writesAbi.filter((n) => !declares(abiTs, n, "Abi"));
check(!missingAbi.length, `every promised ABI export is present (${writesAbi.length})`,
  missingAbi.length ? `missing: ${missingAbi.join(", ")} — run \`npm run compile\`` : "");
const missingBytecode = writesBytecode.filter((n) => !declares(bytecodeTs, n, "Bytecode"));
check(!missingBytecode.length, `every promised bytecode export is present (${writesBytecode.length})`,
  missingBytecode.length ? `missing: ${missingBytecode.join(", ")} — run \`npm run compile\`` : "");

// A truncated or half-written generation is worse than a missing one.
const emptyAbis = writesAbi.filter((n) => new RegExp(`export const ${n}Abi = \\[\\]`).test(abiTs));
check(!emptyAbis.length, "no ABI was exported empty", emptyAbis.join(", "));
const shortBytecode = [...bytecodeTs.matchAll(/export const (\w+)Bytecode = "(0x[0-9a-fA-F]*)"/g)]
  .filter(([, , hex]) => hex.length < 200)
  .map(([, n]) => n);
check(!shortBytecode.length, "no deploy bytecode is suspiciously short", shortBytecode.join(", "));

// The contracts the deploy scripts actually instantiate must have bytecode.
const DEPLOYED = ["tesseraPool", "tesseraVault", "tesseraRouter", "tesseraFeeCollector", "tesseraAmm"];
const notDeployable = DEPLOYED.filter((n) => !declares(bytecodeTs, n, "Bytecode"));
check(!notDeployable.length, `every contract pool:arc deploys has bytecode (${DEPLOYED.length})`,
  notDeployable.join(", "));

// --- 2. exact ---------------------------------------------------------------

if (EXACT) {
  // Requires `npm run compile` to have run first. Any diff means the committed
  // files are not what the current sources compile to.
  let diff = null;
  try {
    diff = execFileSync("git", ["status", "--porcelain", "shared/src/abi.ts", "shared/src/bytecode.ts"], {
      cwd: ROOT,
      encoding: "utf8",
    }).trim();
  } catch (e) {
    check(false, "could not ask git whether the generated files changed", String(e.message).slice(0, 90));
  }
  if (diff !== null) {
    check(
      diff === "",
      "compiling reproduces the committed ABI and bytecode exactly",
      diff ? `${diff.split("\n").length} file(s) differ — commit the result of \`npm run compile\`` : "",
    );
  }
} else {
  console.log("NOTE — structural checks only. Pass --compiled after `npm run compile` for the exact check.");
}

console.log("");
console.log(fails ? `${fails} FAILURE(S)` : "ALL ABI CHECKS PASSED");
process.exit(fails ? 1 : 0);
